# Generated by Django 5.1.3 on 2025-04-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0003_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='İptal Kodu (6 Hane)'),
        ),
    ]
