# Generated by Django 5.1.3 on 2025-04-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hizmet Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('duration', models.PositiveIntegerField(verbose_name='Süre (dakika)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Fiyat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='Bitiş Zamanı')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Müşteri Telefonu')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Müşteri E-posta')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='randevu.service', verbose_name='Seçilen Hizmet')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['start_time'],
            },
        ),
    ]
