# Generated by Django 5.1.3 on 2025-04-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], unique=True, verbose_name='Haftanın Günü')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Kapalı mı?')),
            ],
            options={
                'verbose_name': 'Çalışma Saati',
                'verbose_name_plural': 'Çalışma Saatleri (Haftalık)',
                'ordering': ['day_of_week'],
            },
        ),
    ]
