# Generated by Django 5.1.3 on 2025-04-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0002_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Randevu Sistemi', max_length=100, verbose_name='Site Adı')),
                ('logo', models.ImageField(blank=True, help_text='Otomatik boyutlandırılmaz. İdeal boyut ~120x32 piksel.', null=True, upload_to='site_logos/', verbose_name='Site Logosu (Header için)')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
