# Generated by Django 5.1.3 on 2025-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0005_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(related_name='appointments', to='randevu.service', verbose_name='Seçilen Hizmetler'),
        ),
    ]
