# Generated by Django 5.1.3 on 2025-04-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0006_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_time'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Çalışma Saati', 'verbose_name_plural': 'Çalışma Saatleri'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='İptal Kodu'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Müşteri Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Müşteri Telefon'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='confirmed', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_logos/', verbose_name='Site Logosu'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat'),
        ),
    ]
